export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_ERROR = "GET_STUDENT_ERROR";

export const GET_ENROLL_REQUEST = "GET_ENROLL_REQUEST";
export const GET_ENROLL_SUCCESS = "GET_ENROLL_SUCCESS";
export const GET_ENROLL_ERROR = "GET_ENROLL_ERROR";
